package com.dron.sender.pattern.models.strategy;

public enum ControllerActionStrategy {
	INITIALIZE,
	NEW_UI_SEQUENCE,
	FILL_ROOT_CONTROLS,
	FILL_UI_PLUGIN_ACCORDION,
	NEW_UI_PLUGIN,
	SEND_SEQUENCE,
	PREPARE_SEQUENCE,
	IMPORT_SEQUENCE,
	EXPORT_SEQUENCE;
}
