package com.dron.sender.pattern.models.transformers;

public enum TransformKey {
	HTTP_HEADERS_INTO_UI_HEADERS, PARAMS_INTO_UI_PARAMS, FUTURE_PARAMS_INTO_UI_FUTURE_PARAMS, FILL_PLUGIN_FUTURE_PARAMS, FILL_TITLED_PANES_WITH_FUTURE_PARAMS;
}
